### ISSUE TITLE
Possible error:  50 weeks not 52 weeks

### ISSUE THREAD

**Issue by expanse55** [UKGovernmentBEIS/beis-spl-planner#259]
# Applicability
This issue only applies if this repo relates to the planner here: https://www.plan-shared-parental-leave.service.gov.uk
If not, please disregard the issue.

# Issue
1. The planner
"You can split a total of *52 weeks* as Maternity Leave or Shared Parental Leave."
https://www.plan-shared-parental-leave.service.gov.uk/planner

2. The rules
"You can share up to *50 weeks* of leave"
https://www.gov.uk/shared-parental-leave-and-pay/what-youll-get

I think 1. may be incorrect and 2. correct, although I may have misunderstood. If there is an error, your planner is telling people they have more leave than they are entitled to.

In the planner, perhaps the mandatory 2 weeks maternity leave were included in the shared parental leave.

**Comment by lambley** [comment]
Thanks for reporting this issue @expanse55. I've checked with the team - 52 weeks is the total number of weeks allowed for Maternity/Shared Leave, although the first 2 weeks of Maternity Leave must taken by the Mother/Primary Adopter. 

In this case, both our correct - there are 52 weeks in total available but only 50 can be shared. We will look into a way of making the wording clearer.

**Comment by expanse55** [comment]
Hi - Thanks!

I would like to say again I appreciate the planner. I would find helpful to have clearer wording, definitely.

It is not correct "**52 weeks** is the total number of weeks allowed for Maternity/**Shared Leave**"

**52 weeks** of **shared leave** is not allowed.

This is because, 2 weeks of maternity leave, is compulsory and cannot be shared.

That is why **50 weeks of shared leave is allowed** as stated on gov.uk (https://www.gov.uk/shared-parental-leave-and-pay/what-youll-get) or 52 weeks of maternity leave is allowed.

You can't smush it all together in one statement and say "52 weeks is the total number of weeks allowed for Maternity/**Shared Leave**".

Thank you for looking at my ticket and considering a change in the wording on the planner.
